version: "3.3"
services:
  frontend-cypress:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /home/ubuntu/code/frontend-cypress/tests/e2e/screenshots:/usr/src/app/tests/e2e/screenshots
      - /home/ubuntu/code/frontend-cypress/tests/e2e/videos:/usr/src/app/tests/e2e/videos
